[package]
name = "r2sleigh-lift"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Sleigh to r2il translator"

[dependencies]
r2il = { path = "../r2il" }
libsla.workspace = true
sleigh-config.workspace = true
thiserror.workspace = true

[features]
x86 = ["sleigh-config/x86"]

[[example]]
name = "win32_census"
required-features = ["x86"]

[dev-dependencies]
serde_json = "1"
